### ISSUE TITLE
[API] Récupérer la liste des villes et des pays

### ISSUE THREAD

**Issue by floweb** [EuskalMoneta/dolibarr#1]
- Ville
- Pays

**Comment by floweb** [comment]
Sur le même sujet, je vois qu'il est indiqué dans le ticket Odoo:

> Une fois le code postal saisi, la liste des villes correspondantes doit être proposée dans une liste déroulante. Cette règle s'applique uniquement pour la France.

A l'heure actuelle, l'API Dolibarr ne fournit pas (à ma connaissance) de moyen de faire une recherche sur les villes selon un code postal, faudra-t-il implémenter ça dans notre API ou dans Dolibarr ?

**Comment by floweb** [comment]
Plus important encore, je note également que le ticket Odoo ne parle des Départements !

Hors ils sont bien mentionnés dans l'étude fonctionnelle et dans les fiches adhérents de Dolibarr, je pense que c'est une chose de plus à ajouter dans l'API Dolibarr, dois-je modifier cette issue ?

**Comment by Xebax** [comment]
Livré dans le commit 7acb6ded700ab95cf303eba707ab68874a490dc9
Les éléments suivants ont été ajoutés dans l'API REST :
- GET /countries
- GET /countries/{id}
- GET /towns

Voir REST API Explorer pour les détails.
