### ISSUE TITLE
Docker container does not work over ssh -L

### ISSUE THREAD

**Issue by CreativeCactus** [EuskalMoneta/dolibarr#7]
# Bug
After setting up docker container:
127.0.0.1:forwardedPort
```
Warning: preg_match(): No ending delimiter '/' found in /var/www/html/filefunc.inc.php on line 95

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/filefunc.inc.php:95) in /var/www/html/filefunc.inc.php on line 121
```

## Environment
- **Version**: latest docker container as of now
- **OS**: ubuntu server, via ssh -L

**Comment by Xebax** [comment]
Please submit issues upstream. See https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md
